name: gestionsalle
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  datetime_picker_formfield: ^1.0.0
  dropdownfield: ^1.0.0
  combos: ^1.2.0
  toast: ^0.1.5
  #date_field: ^0.3.3
  json_model: ^0.0.2
  flutter_pagewise: ^1.2.3
  #path_provider: ^1.6.27
  network_to_file_image: ^2.2.8
  font_awesome_flutter: 8.8.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  flare_splash_screen: ^2.1.2
  

dev_dependencies:
  http: ^0.12.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # example:
  fonts:
    - family: LunaSans
      fonts:
        - asset: assets/fonts/LunaSans-Black.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
      
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
